apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tektoncd-catalog
  namespace: default
spec:
  interval: 1h
  url: https://github.com/tektoncd/catalog
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/pipeline/  
    !/task/
    # exclude test directories
    /task/*/*/tests
    # exclude samples directories
    /task/*/*/samples