apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: chicken
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/taylorshaulis/chicken
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/  
    !/tekton/  
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-jobs
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./tekton/local-flux/hello-jobs
      sourceRef:
        kind: GitRepository
        name: chicken
        namespace: flux-system
      interval: 1m
  values:
    helloworld:
      task:
        enabled: true
      taskrun:
        enabled: true