apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: chicken
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/taylorshaulis/chicken
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/    
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echoserver
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/echoserver
      sourceRef:
        kind: GitRepository
        name: chicken
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2