apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus
  namespace: default
spec:
  sourceRef:
    kind: GitRepository
    name: flux2
  path: ./manifests/monitoring/kube-prometheus-stack
  prune: true
  wait: true