apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tekton
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/taylorshaulis/tekton-helm-chart
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/    
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tekton
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/tekton-pipeline
      sourceRef:
        kind: GitRepository
        name: tekton
        namespace: flux-system
      interval: 1m