apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: vault
  namespace: default
spec:
  interval: 5m
  url: https://github.com/hashicorp/vault-helm
  ref:
    branch: main 
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./
      sourceRef:
        kind: GitRepository
        name: vault
        namespace: default
      interval: 5m