controller:
  service:
    enableHttps: false
    external:
      enabled: false
    internal:
      enabled: true
      annotations:
        # Create internal ELB
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"