

apps:
  - name: echoserver
    namespace: default
    project: default
    repoUrl: https://github.com/taylorshaulis/chicken.git
    path: charts/echoserver
    targetRevision: HEAD

  - name: aws-load-balancer
    namespace: kube-system
    project: default
    repoUrl: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: "1.4.4"
    helm: |
      parameters:
        - name: clusterName
          value: my-cluster

  - name: ingress-nginx
    namespace: kube-system
    project: default
    repoUrl: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: "4.1.2"
    helm: |
      values: |
        {{ .Files.Get "ingress_nginx.values.yaml" | nindent 2}}

  - name: argo-workflows
    namespace: argocd
    project: default
    repoUrl: https://github.com/argoproj/argo-helm
    path: charts/argo-workflows
    targetRevision: "argo-workflows-0.19.4"
    helm: |
      values: |
        {{ .Files.Get "argo_workflows.values.yaml" | nindent 2}}



spec:
  destination:
    server: https://kubernetes.default.svc