apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: chicken
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/taylorshaulis/chicken
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/  
    !/tekton/  