apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tektoncd-catalog
  namespace: default
spec:
  interval: 1m
  dependsOn:
    - name: tekton
  chart:
    spec:
      chart: ./tekton/tektoncd-catalog
      sourceRef:
        kind: GitRepository
        name: chicken
        namespace: flux-system
      interval: 1m