{{- if .Values.clonebuildpush.pipeline.enabled }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
spec:
  description: | 
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry
  params:
  - name: repo-url
    type: string
  - name: cmd
    type: string
  workspaces:
  - name: shared-data
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: listdata
    taskRef:
      hellocmd
    workspaces:
    - name: data
      workspace: shared-data
    params:
    - name: cmd
      value: |
        #!/bin/sh
        ls -alh /data
{{- if .Values.clonebuildpush.pipelinerun.enabled }}
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clone-build-push-run
spec:
  pipelineRef:
    name: clone-build-push
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
  - name: repo-url
    value: {{ .Values.clonebuildpush.pipelinerun.repourl }}
{{ end }}
{{ end }}